name: Build libVLCUnityPlugin for Android arm64

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-libvlcunify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Android SDK and NDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '8512546'
          ndk-version: '21.4.7075529'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build meson pkg-config

      - name: Copy prebuilt libs and headers into NDK sysroot
        run: |
          API_LEVEL=21
          SYSROOT_LIB="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/$API_LEVEL"
          SYSROOT_INC="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include"

          mkdir -p "$SYSROOT_LIB" "$SYSROOT_INC"

          # 复制预编译 libvlc.so 和 libc++_shared.so
          cp prebuild/libs/arm64/libvlc.so "$SYSROOT_LIB/"
          cp prebuild/libs/arm64/libc++_shared.so "$SYSROOT_LIB/"

          # 复制 libvlc 头文件
          cp -r prebuild/includes/* "$SYSROOT_INC/"

          echo "Installed libvlc.so and headers into NDK sysroot"

      - name: Write Meson cross file
        run: |
          cat > android_arm64_clang.txt <<EOF
          [binaries]
          c = ${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
          cpp = ${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++
          ar = ${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
          strip = ${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip

          [host_machine]
          system = 'android'
          cpu_family = 'aarch64'
          cpu = 'aarch64'
          endian = 'little'
          EOF

      - name: Configure Meson build
        run: |
          meson setup builddir --cross-file=android_arm64_clang.txt \
            --prefix=$(pwd)/install

      - name: Build libVLCUnityPlugin.so
        run: |
          meson compile -C builddir

      - name: Collect libVLCUnityPlugin.so
        run: |
          mkdir -p release_files
          cp builddir/PluginSource/libVLCUnityPlugin.so release_files/

      - name: Zip and upload
        run: |
          cd release_files
          zip ../vlc-unity-plugin.zip *

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: vlc-unity-plugin.zip
          tag_name: vlc-unity-plugin-v${{ github.run_number }}
